apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
    component: rrdcached
  ports:
    - name: rrdcached
      port: 42217
      targetPort: 42217
      protocol: TCP
