apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
    component: rrdcached
  ports:
    - name: rrdcached
      port: {{ .Values.service.port }}
      targetPort: 42217
      protocol: TCP
